name: Test

on:
  pull_request: null
  push:
    branches:
    - master

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        template:
        - get-opt-cli
        - lib-extensible
        - mix-cli
        - optparse-applicative-cli

    steps:
    - uses: actions/checkout@v2

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-
    - uses: haskell/actions/setup@v1.1.6
      name: Setup Haskell
      with:
        ghc-version: 8.8.4
        enable-stack: true
        stack-version: 'latest'

    - name: Build templat
      run: |
        stack new sample ${{ matrix.template }}
        cd sample
        stack --system-ghc test
