name: Test

on:
  pull_request: null
  push:
    branches:
    - master

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        template:
        - mix-cli-with-bazel

    steps:
    - uses: actions/checkout@v2

    - name: Cache Bazel
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-${{ hashFiles('WORKSPACE') }}

    - uses: haskell/actions/setup@v1.1.6
      name: Setup Haskell
      with:
        ghc-version: 8.8.4
        enable-stack: true
        stack-version: 'latest'

    - name: Build templat
      run: |
        stack new sample ${{ matrix.template }}
        cd sample
        bazelisk run //:sample
